variables: _variables_example.yaml
tasks:
  opencd-free-0:
    html_rss:
      url: https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=0
      user-agent: '{? headers.user_agent ?}'
      cookie: '{? headers.cookie ?}'
      params: '{? headers.params ?}'
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="plugin_details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'img[class*="pro_free"]'
          attribute: alt
        deadline:
          element_selector: 'div:has(>img[class*="pro_free"])+span'
          attribute: title
        progress:
          element_selector: 'div.progress'
          attribute: class
    no_entries_ok: yes
    if:
      - progress!='': reject
      - not promotion in ['Free','2X Free']: reject
      - promotion in ['Free','2X Free']:
          if: 
            - "deadline|parsedate - now < timedelta(hours=4)": reject
            - "deadline|parsedate - now > timedelta(hours=4)": accept
    download: '{? download_path ?}'

  opencd-free-1:
    html_rss:
      url: https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=1
      user-agent: '{? headers.user_agent ?}'
      cookie: '{? headers.cookie ?}'
      params: '{? headers.params ?}'
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="plugin_details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'img[class*="pro_free"]'
          attribute: alt
        deadline:
          element_selector: 'div:has(>img[class*="pro_free"])+span'
          attribute: title
        progress:
          element_selector: 'div.progress'
          attribute: class
    no_entries_ok: yes
    if:
      - progress!='': reject
      - not promotion in ['Free','2X Free']: reject
      - promotion in ['Free','2X Free']:
          if: 
            - "deadline|parsedate - now < timedelta(hours=4)": reject
            - "deadline|parsedate - now > timedelta(hours=4)": accept
    download: '{? download_path ?}'