variables: _variables_pterclub.yaml
templates:
  global:
    include: _templates_global.yaml
tasks:
  pterclub-official-free:
    html_rss_plus:
      urls: 
        - https://pterclub.com/torrents.php?tag_internal=yes # 官种
      user-agent: '{? headers.user_agent ?}'
      cookie: '{? headers.cookie ?}'
      params: '{? headers.params ?}'
      url_interval: 2
      torrent_limited: 30
      root_element_selector: 'table.torrents tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'img[class*="pro_free"]'
          attribute: alt
        deadline:
          element_selector: 'div:has(>a>img[class*="pro_free"])>b>span'
          attribute: title
        progress:
          element_selector: 'img[class*="progbar"]'
          attribute: class
    no_entries_ok: yes
    if:
      - progress!='': reject
      - not promotion in ['Free','2X Free']: reject
      - promotion in ['Free','2X Free']:
          if: 
            - "deadline==''": accept
            - "deadline!='' and deadline|parsedate - now < timedelta(hours=6)": reject
            - "deadline!='' and deadline|parsedate - now > timedelta(hours=6)": accept

    template:
      - global
    # download: '{? download_path ?}'