variables: _variables_opencd.yaml
templates:
  global:
    include: _templates_global.yaml
tasks:
  opencd-free:
    html_rss_plus:
      urls: 
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=0
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=1
      user-agent: '{? headers.user_agent ?}'
      cookie: '{? headers.cookie ?}'
      params: '{? headers.params ?}'
      url_interval: 2
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="plugin_details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'img[class*="pro_free"]'
          attribute: alt
        deadline:
          element_selector: 'div:has(>img[class*="pro_free"])+span'
          attribute: title
        progress: # 注意该值是一个列表
          element_selector: 'div.progress'
          attribute: class
    no_entries_ok: yes
    if:
      - progress!='': reject
      - not promotion in ['Free','2X Free']: reject
      - promotion in ['Free','2X Free']:
          if:
            - deadline=='': reject
            - deadline!='':
                if: 
                  - '(deadline+"+08:00")|parsedate - now.astimezone() < timedelta(hours=6)': reject
                  - '(deadline+"+08:00")|parsedate - now.astimezone() > timedelta(hours=6)': accept

    template:
      - global