variables: _variables_agsvpt.yaml
templates:
  global:
    include: _templates_global.yaml
tasks:
  agsvpt-official-free:
    html_rss_plus:
      urls: 
        #- https://www.agsvpt.com/torrents.php?tag_id=3 # 官种
        - https://www.agsvpt.com/torrents.php?cat=419 # 以下是短剧，所有短剧都是冰种，所以暂时不写官种过滤规则
        - https://www.agsvpt.com/torrents.php?inclbookmarked=0&incldead=1&spstate=0&cat=419&page=1
        - https://www.agsvpt.com/torrents.php?inclbookmarked=0&incldead=1&spstate=0&cat=419&page=2
        - https://www.agsvpt.com/torrents.php?inclbookmarked=0&incldead=1&spstate=0&cat=419&page=3
        - https://www.agsvpt.com/torrents.php?inclbookmarked=0&incldead=1&spstate=0&cat=419&page=4
        - https://www.agsvpt.com/torrents.php?inclbookmarked=0&incldead=1&spstate=0&cat=419&page=5
        - https://www.agsvpt.com/torrents.php?inclbookmarked=0&incldead=1&spstate=0&cat=419&page=6
      user-agent: '{? headers.user_agent ?}'
      cookie: '{? headers.cookie ?}'
      params: '{? headers.params ?}'
      url_interval: 2
      root_element_selector: 'table.torrents tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href^="download.php"]'
          attribute: href
        promotion:
          element_selector: 'img[class*="pro_free"]'
          attribute: alt
        deadline:
          element_selector: 'td:has(>img[class*="pro_free"])>font>span'  # 等待修复，目前处于站免期间，无法测试
          attribute: title
        progress:
          element_selector: 'div[title*="seeding"]'
          attribute: title
    no_entries_ok: yes
    limit_new: 200
    if:
      - progress!='': reject
      - not promotion in ['Free']: reject
      - promotion in ['Free']:
         if:
           - deadline=='': reject
           - deadline!='':
               if: 
                 - '(deadline+"+08:00")|parsedate - now.astimezone() < timedelta(hours=6)': reject
                 - '(deadline+"+08:00")|parsedate - now.astimezone() > timedelta(hours=6)': accept
    template:
      - global
