# 重新下已完成但HR没合格的种子
variables: _variables_opencd.yaml
templates:
  global:
    include: _templates_global.yaml
tasks:
  opencd-free:
    html_rss_plus:
      urls: 
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=0
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=1
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=2
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=3
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=4
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=5
        - https://open.cd/torrents.php?inclbookmarked=0&incldead=1&spstate=0&option-torrents=0&page=6
      user-agent: '{? headers.user_agent ?}'
      cookie: '{? headers.cookie ?}'
      params: '{? headers.params ?}'
      url_interval: 1
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="plugin_details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        progress: # 注意该值是一个列表
          element_selector: 'div.progress_completed_hr'
          attribute: class
    no_entries_ok: yes
    if:
      - "not 'progress_completed_hr' in progress": reject
      - "'progress_completed_hr' in progress": accept

    download: ./downloads